version: '3'

services:
  db:
    image: arm64v8/postgres
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./db/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432